language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then travis_retry pip install unittest2

script:
  - cd tests
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then unit2 discover
  - python -m unittest discover

notifications:
  email:
    on_success: never
    on_failure: always