language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then travis_retry pip install unittest2; fi
  - pip install -r requirements.txt

script:
  - pip install https://github.com/laike9m/ezcf/archive/master.zip
  - cd tests
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then unit2 discover; fi
  - if [[ $TRAVIS_PYTHON_VERSION > 2.6 ]]; then python -m unittest discover; fi
  - cd ../tests2
  - python run_test.py

notifications:
  email:
    on_success: never
    on_failure: always